apiVersion: v1beta1
kind: AgentConfig
metadata:
  name: sno
rendezvousIP: 192.168.217.141
hosts:
  - hostname: sno-master-0
    role: master
    interfaces:
      - name: ens33
        macAddress: "YOUR:ACTUAL:MAC"
